### ISSUE TITLE
Delete account feature

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#106]
We need to enable people to delete their account from chain if they want to.
- User should be able to delete his account by signing and submitting deleteAccount tx.
- User's karma coin balance should be burned or moved to a community pool account.
- We need to make sure this feature is not misused to get multiple signup rewards due to multiple singups and deletions.
One way to achieve this is by storing on-chain an index of hashes of phone numbers of deleted accounts and not apply signup reward on new signup when a hash of the new user's phone number is in the index.

**Comment by HolyGrease** [comment]
Account deletion and moving of funds to one of foundation accounts - verifier, sudo, etc…
