### ISSUE TITLE
Treasury and slashing use cases

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#140]
We need to verify that slashing for misbehaving nodes such as nodes that go offline for long time is working as expected. I've got a GC node that is paused on TN2 but I don't see any past or pending slashes.

**Comment by avive** [comment]
Include testing that slashed coin goes to treasury as configured in chainspec and we need to remember to configure treasury for testnets and mainnet. See: `All slashed tokens are added to the [Treasury](https://wiki.polkadot.network/docs/learn-treasury). This way, tokens from malicious actors can be used to reward community members who actively help build the network and ecosystem.` here: https://support.polkadot.network/support/solutions/articles/65000110858-what-does-it-mean-to-get-slashed-

**Comment by avive** [comment]
add treasury pallet task.

**Comment by avive** [comment]
1. When user deletes account - move funds to treasury.
2. Sudo should be able to transact in/out of treasury account.
3. When validator is slashed - move funds to treasury.

**Comment by HolyGrease** [comment]
https://github.com/karma-coin/karmachain/pull/145
