### ISSUE TITLE
Dart support for nomination pools

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#144]
- Support all nomination pool RPC calls for reading data.
- Support all nomination pools calls/txs for executing actions.

**Comment by HolyGrease** [comment]
Substrate doc for nomination pools API  https://github.com/paritytech/substrate/blob/master/frame/nomination-pools/src/lib.rs#L18

**Comment by HolyGrease** [comment]
Complete in https://github.com/avive/karmacoin-app/pull/8
