### ISSUE TITLE
Update validation flow

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#151]
Solution outline
- Replace the dart-based authenticator with a new rust grpc service that is currently deployed for KC1.
- Check signature on response to verify authenticator public key is in chainspec / genesis config.
- Change client api to include session_id param - needed for the verification process - pass to authenticator.

Ref:
Checked VerifyNumberEx() and SendVerificationCode().

1. Client calls send verification code to a mobile number. Authenticator uses Twilio api to send code via whatsapp and returns a session_id.
- Client needs to pass this session_id to the NewUserTx call.
- Impl of NewUserTx should call VerifyNumberEx() to obtain the authenticator evidence.

We might consider adding a version of VerifyNumberEx() that returns a signed scale-encoded response that can be included in the tx...

**Comment by avive** [comment]
I'm going to implement a stand-alone verifier today and will share the repo. You will need to assist with scale-encoding and signing responses.

**Comment by HolyGrease** [comment]
Do we need this? I think we can remove verifier RPC API from the chain as we have new verifier service for this

**Comment by avive** [comment]
You are right. No longer valid.

**Comment by avive** [comment]
Remaining tasks:
- [ ] code complete new validator (return scale-encoded signed result to validate call) and test locally
- [ ] deploy new stand-alone validator and configure https on GC (devops)
- [ ] use new validator from kc2 client.

**Comment by avive** [comment]
Please deploy....

**Comment by avive** [comment]
Can be complete after bug fix to verifier is deployed.
