### ISSUE TITLE
Working shell script for local devnet for tests

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#155]
Update  devnet.sh to do the following:
1. Start local net with one node in own process and direct output to a log file and not to console.
2. Run the 2 RPC commands as soon as node starts - maybe a short delay is needed?

The idea is to have 1 command to start node for running integration tests in the app repo.

**Comment by HolyGrease** [comment]
I don't see any `devnet.sh` file either in `scripts` folder or just in project root. So what file are we talking about?

**Comment by avive** [comment]
Here she is: https://github.com/karma-coin/karmachain/blob/main/scripts/devnet.sh
