### ISSUE TITLE
Register netId

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#158]
- We should have a registered netId for mainnet in the polkadot registry.
- Ideally we can use a different netId for testnets to avoid address confusion between networks.
- We need to add address validation method in Dart that validates that and ss58 address is a valid address for a given netId.
- We need to add support in dart config to connect to currently running testnet or mainnet.

**Comment by HolyGrease** [comment]
According to substrate comments that I found in ss58-registry repo the 42 prefix is used for all testate networks

**Comment by HolyGrease** [comment]
Here the PR for registered our netId
https://github.com/paritytech/ss58-registry/pull/185

**Comment by avive** [comment]
Very cool. So mainnet id will be 21 and 42 for testnets. Correct?

**Comment by HolyGrease** [comment]
Yes correct

**Comment by HolyGrease** [comment]
Done in https://github.com/avive/karmacoin-app/pull/16
