### ISSUE TITLE
Wrongly quoted branch

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#19]
https://github.com/karma-coin/karmachain/blob/b6824f2694657a13c3384e32cbbf7a8000bc39d0/frame/identity/Cargo.toml#L18

"branch" => branch

**Comment by HolyGrease** [comment]
Fixed in [408030e](https://github.com/karma-coin/karmachain/commit/408030e45784c56cd7e2fd2b62fbee70f3c0ab75)
