### ISSUE TITLE
Accounts interoperability

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#190]
Accounts created by the app must be compatible with accounts created in webui using same seed.
Currently, the same seed create 2 different public addresses.
1. Go to app, create account. Go to menu and choose backup account and click the copy icon to copy the seed to clipboard.
2. Go to polkadot.js, create new account from seed and paste the seed.

Result: public addresses are different.
Expected: same public address as generated by the app.

Note: The app is currently using bip39 in keyring to generate the seed from the mnemonic w/o a passphrase and generates an ed25519 keypair for it. Is this what the polkadot.js wallet using? Look at KC2KeyRing() in keyring.dart.

This happens even if the account network is set to 'Karmacoin TN 3' when creating the account from seed in the wallet.

**Comment by HolyGrease** [comment]
The problem is that polkadot js extension use sr25519 scheme for sign transactions while our Dart app use ed25519. And we do not have any options to change it. polkadot js extrension can only use sr25519 while Dart do not have any library with sr25519 scheme
