### ISSUE TITLE
Transaction pool

### ISSUE THREAD

**Issue by HolyGrease** [karma-coin/karmachain#36]
Implement transaction with custom logic. Appreciation transaction should wait until new user transaction happen

**Comment by HolyGrease** [comment]
I find the way to implement custom transaction ordering while using default substrate transaction pool. So when we validate `appreciation` transaction and user is not register yet we can set special tag, that this transaction requires. And when validating `new_user` transaction set that this transaction provide some tag.

Appreciation transaction requires tag encoded from appreciation receiver number `to`
```rust
let requires = vec![Encode::encode(&(to))];
```

And `new_user` transaction provide this tag:

```rust
let provides = vec![Encode::encode(&(number))];
```

**Comment by avive** [comment]
Cool but I need to better understand this solution.

**Comment by HolyGrease** [comment]
I think we can discus it today
