### ISSUE TITLE
Implement Karma Rewards

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#48]
- See kc 1.0 as a working ref implementation.
- Add rpc method GetLeaderBoard() - returns list of users allegeable for the current round of karma rewards with basic info for each - see KC 1.0 for reference.

Ref https://karmaco.in/docs/tokenomics#karma-rewards

**Comment by avive** [comment]
as we discussed today - let's put this on hold for now until first version of the testnet is out.

**Comment by HolyGrease** [comment]
We should implement RPC method `get_leader_board` here!
