### ISSUE TITLE
Implement account migration

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#56]
Sign up tx processing logic changes to support this feature:
If there's an existing on-chain account for user-provided verified phone number then migrate old account data - score, balance, appreciations, communities, user-name to new account and delete the old account from the chain!
In this case, ignore the user-provided requested user-name and just use the existing user name. User can change his user name later via the app.

References:

- https://karmaco.in/docs/app/release-notes/#new-features
- https://github.com/karma-coin/karmacoin-server/blob/main/crates/server/src/services/blockchain/new_user_tx_processor.rs

**Comment by HolyGrease** [comment]
#62 implements this
