### ISSUE TITLE
Implement validators rewards algo and emit events

### ISSUE THREAD

**Issue by HolyGrease** [karma-coin/karmachain#6]
- Implement the validators rewards so it follows our economic model and issuance curve (shared with D)
- Emit validator rewards events for block producing and block finalization
- Write lots of tests to validate correctness

**Comment by HolyGrease** [comment]
Have some problems with implementing validators rewards according to curve that we have `f(x) = 10_000_000 * exp(-1 * 0.020036 * x)`. Substrate do not allow float arithmetic due it is not deterministic. So instead of that exp we can use approximate function like `f(x) = 10_000_000 * (0.020036^x)` or if we need more precision we can modify It with predefined amounts like
```
const VALUES: [u32; 256] = [/* pre-computed values of payout */];
```

**Comment by avive** [comment]
This is fine.
