### ISSUE TITLE
Add Karmacoin to polkadot-js.apps

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#85]
As part of going live with TN1 we should add support for Karmachain to https://polkadot.js.org/apps via issuing a PR to https://github.com/polkadot-js/apps/tree/master/packages/apps-config#README.md
We should provide
- Custom logo
- Custom color
- Testnet public node endpoint
- Perhaps even custom API for typed txs and RPCs

**Comment by avive** [comment]
I can't even get https://github.com/polkadot-js/apps to build on my dev box. Tried their release tag of master.

**Comment by HolyGrease** [comment]
For me works fine. Use build in docker, see following commands:
```bash
docker build -t jacogr/polkadot-js-apps -f docker/Dockerfile .
```

```bash
docker run --rm -it --name polkadot-ui -e WS_URL=ws://someip:9944 -p 80:80 jacogr/polkadot-js-apps:latest
```

**Comment by HolyGrease** [comment]
@avive, please provide logo, colour and endpoints. I finish this issue

**Comment by avive** [comment]
Need to know what size and format (png / svg) for logo.
Regarding endpoints - do we just need a domain name for public node of testnet and for mainnet?
If yes, I guess we can use testnet.karmaco.in for testnet and mainnet.karmaco.in for mainnet.

**Comment by avive** [comment]
What else do you need?

**Comment by avive** [comment]
Did we issue the PR?

**Comment by avive** [comment]
Merged!
